# Generated by Django 5.1 on 2024-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_user_alter_todo_description_alter_todo_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=120),
        ),
    ]
