# Generated by Django 5.1 on 2024-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "낮음"), (2, "중간"), (3, "높음")], default=2
            ),
        ),
    ]
