# Generated by Django 5.1 on 2024-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="gerne",
            field=models.CharField(default=1, max_length=100, verbose_name="장르"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(default=1, verbose_name="요약"),
            preserve_default=False,
        ),
    ]
