# Generated by Django 5.1 on 2024-08-12 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_gerne_book_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="gerne",
            new_name="genre",
        ),
    ]
