# Generated by Django 5.1 on 2024-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_rename_gerne_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
    ]
